name: Macro-Sea
author: M R
url: https://macro-sea.netlify.com/
hover_color: "#1cd41c"
info: >-
  Macro Sea is a creative developer based in New York City.


  Our mission is to do projects that we find interesting.


  We design, build, and operate projects for people and places that we care about.


  Created in 2009, Macro Sea has executed projects in the built environment and conceptual realms, in New York City and around the world.


  As part of our core mission, Macro Sea conceptualizes and builds creative interim use projects that transform and energize our surroundings. Our design projects have been featured in MoMA and the Venice Biennale.


  Macro Sea exists as a series of ongoing collaborations between experts in a wide variety of disciplines including artists, architects, designers, lawyers and others. The company has served as the entrepreneurial framework for most of David Belt’s development pursuits since 2009.
