backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: mimecine/neat-macro-sea
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:      
  - label: "Projects"
    label_singular: "Project"
    name: "projects"
    folder: "src/projects"
    create: true
    delete: true
    editor:
      preview: false
    summary: "{{title}}"
    sortable_fields: ['order','title']

    fields:
      - {label: "Hidden", name: "draft", widget: "boolean", default: false }
      - {label: "Title", name: "title", widget: "string" }
      - label: "Category"
        name: "tags"
        widget: relation
        collection: "category"
        value_field: "title"
        search_fields: ["title"]
        multiple: true
      # - widget: list
      #   label: "Category"
      #   name: tags
      #   required: false
      - {label: "Ordering", name: "order", widget: "number", required: false, default: 0 }
      - {label: "Description", name: "body", widget: "markdown", required: false }
      - {label: "Credits", name: "credits", widget: "markdown", required: false }
      - label: "Images"
        name: "images"
        widget: "list"
        summary: '{{fields.image}}'
        fields:
          - {label: "Image", name: "image", widget: "image" }

  - label: "Categories"
    label_singular: "Category"
    name: "category"
    folder: "src/categories"
    create: true
    delete: true
    editor:
      preview: false
    summary: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string" }

  - label: "Products"
    label_singular: "Product"
    name: "products"
    folder: "src/products"
    create: true
    delete: true
    editor:
      preview: true
    summary: "{{title}} - {{price}}"
    fields:
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Ordering", name: "order", widget: "number", required: false }
      - {label: "Description", name: "body", widget: "markdown" }
      - {label: "Price", name: "price", widget: "number" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - {label: "Image", name: "image", widget: "image" }
          - {label: "Caption/Alt", name: "caption", widget: "string" }
      - widget: list
        label: tags
        name: tags

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
    - label: "Site"
      name: "site"
      file: "src/_data/settings.yaml"
      fields:
        - { label: "Info", name: "info", widget: "markdown", required: false }
        # - { label: "Hover Color", name: "hover_color", widget: color }
    

